spring.mail.host=smtp.resend.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.starttls.required=true
spring.mail.default-encoding=UTF-8

app.mail.from=KaucjApp <noreply@kaucjapp.pl>

app.base-url=${BASE_URL}
server.port=8084