services:
  kafka:
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/deposit/test" ]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
    volumes:
      - kafka_data:/var/lib/kafka/data

  monitor-db:
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status | grep UN" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

volumes:
  kafka_data: