services:
  kafka:
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
    volumes:
      - kafka_data:/var/lib/kafka/data

  monitor-db:
    healthcheck:
      test: [ "CMD-SHELL", "nodetool status | grep UN" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 90s

volumes:
  kafka_data: