services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=kaucjappdb
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d kaucjappdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: .
      target: builder
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["./mvnw", "test"]


  app:
    build: .
    image: kaucjapp
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      app-test:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kaucjappdb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
