server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/offers_db

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer