server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Azure Blob / Azurite (local emulator)
azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING:DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02NoBQy7Pg8a209Q5SOqt0hX4da6e6e40BE3HIKYe+v805Nd92wN3PRJ7Iv58LsNRYd7d7x6ee8dMnwPQcq33bo2s0dCDSuUi0lHBfDJCHno3ABdAXaio96Utw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;}
azure.storage.container-name=${AZURE_STORAGE_CONTAINER_NAME:profile-pictures}
azure.storage.public-blob-endpoint=${AZURE_STORAGE_PUBLIC_BLOB_ENDPOINT:http://127.0.0.1:10000/devstoreaccount1}
azure.storage.max-file-size-bytes=5242880
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=users-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=pl.isigmas.kaucjapp.*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
