app {
  server {
    host = ${SERVER_HOST}
    port = ${SERVER_PORT}
  }

  kafka {
    bootstrap-servers = ${KAFKA_SERVERS}
    topic = "system-logs"
    group-id = "event-monitor"
  }
}

pekko {
  loglevel = "INFO"
}

ctx {
  keyspace = "monitor_db"
  preparedStatementCacheSize = 1000
  session {
    basic.contact-points = [ ${CASSANDRA_CONTACT_POINTS} ]
    basic.load-balancing-policy.local-datacenter = ${CASSANDRA_DATACENTER}
  }
}