app {
  server {
    host = ${SERVER_HOST}
    port = ${SERVER_PORT}
  }

  kafka {
    bootstrap-servers = ${KAFKA_SERVERS}
    topic = "system-logs"
    group-id = "event-monitor"
  }
}

pekko {
  loglevel = "INFO"
}

ctx {
  dataSourceClassName = "org.postgresql.ds.PGSimpleDataSource"
  dataSource {
    user = ${DATASOURCE_USERNAME}
    password = ${DATASOURCE_PASSWORD}
    databaseName = "monitor_db"
    serverName = "monitor-db"
    portNumber = 5432
  }
 
  connectionTimeout = 30000
  maximumPoolSize = 10
}