app {
  server {
    host = ${SERVER_HOST}
    port = ${SERVER_PORT}
  }

  kafka {
    bootstrap-servers = ${KAFKA_SERVERS}
    topic = "system-logs"
    group-id = "event-monitor"
    security-protocol = ${?KAFKA_SECURITY_PROTOCOL}
    sasl-mechanism = ${?KAFKA_SASL_MECHANISM}
    sasl-jaas-config = ${?KAFKA_SASL_JAAS_CONFIG}
  }
}

pekko {
  loglevel = "INFO"
}

app.db {
  url = ${MONITOR_DB_URL}
  username = ${MONITOR_DB_USERNAME}
  password = ${MONITOR_DB_PASSWORD}
  pool-size = 4
  pool-size = ${?MONITOR_DB_POOL_SIZE}
}