#!/usr/bin/env bash
# Runs on the server (as the "deploy" user) and is invoked by .github/workflows/deploy.yml over SSH.
#
#   deploy.sh deploy <image_tag>   pull + start the stack with this tag; rolls back automatically if it does not become healthy
#   deploy.sh mark-good            record the running tag as the last known good one (after external smoke tests passed)
#   deploy.sh rollback             go back to the last known good tag
#
# Database migrations (Flyway) are not rolled back, so they must stay backward compatible (see AGENTS.md).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

cd "$APP_DIR"
[[ -f "$ENV_FILE" ]] || die "$ENV_FILE is missing (it is generated by the deploy workflow)"

wait_timeout="${DEPLOY_WAIT_TIMEOUT:-420}"

start_stack() {
  local tag="$1"
  export IMAGE_TAG="$tag"

  # Every step has an explicit "|| return 1": this function is called from an "if", where "set -e" is ignored.
  log "Pulling images for tag $tag"
  dc pull --quiet || return 1

  # Infrastructure first, so databases can be created before the services start (idempotent, also for upgrades)
  log "Starting infrastructure"
  dc up -d --wait --wait-timeout 180 postgres redis kafka || return 1
  dc exec -T postgres sh /docker-entrypoint-initdb.d/01-create-databases.sh || return 1

  log "Starting application"
  dc up -d --remove-orphans --wait --wait-timeout "$wait_timeout" || return 1
}

do_rollback() {
  [[ -f .last-good-tag ]] || die "No .last-good-tag recorded, cannot roll back"
  local good
  good="$(cat .last-good-tag)"
  log "Rolling back to $good"
  start_stack "$good"
  printf '%s' "$good" > .current-tag
  log "Rollback finished"
}

case "${1:-}" in
  deploy)
    tag="${2:?usage: deploy.sh deploy <image_tag>}"
    previous="$(current_tag || true)"
    log "Deploying $tag (previous: ${previous:-none})"
    if start_stack "$tag"; then
      printf '%s' "$tag" > .current-tag
      log "Stack is healthy on $tag"
      docker image prune -af --filter "until=24h" >/dev/null 2>&1 || true
    else
      log "Deployment of $tag failed, collecting logs"
      dc ps || true
      dc logs --tail 40 || true
      if [[ -f .last-good-tag ]]; then
        do_rollback
      fi
      exit 1
    fi
    ;;
  mark-good)
    current_tag > .last-good-tag
    log "Marked $(cat .last-good-tag) as last known good"
    ;;
  rollback)
    do_rollback
    ;;
  *)
    die "usage: deploy.sh {deploy <image_tag>|mark-good|rollback}"
    ;;
esac
