server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:classpath:application-local.yml
  threads:
    virtual:
      enabled: true

gateway:
  routes:
    - id: users-services
      path: /api/users/**
      uri: http://localhost:8081
    - id: offers-service
      path: /api/offers/**
      uri: http://localhost:8082
    - id: auth-service
      path: /api/auth/**
      uri: http://localhost:8083

jwt:
  secret: ${JWT_SECRET}