name: Docker Build and Test - backend

on:
  push:
    branches: [ "main", "backend" ]
  pull_request:
    branches: [ "main", "backend" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Pull source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run Spring Boot Tests (including Testcontainers)
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TESTCONTAINERS_RYUK_DISABLED: true
        run: ./mvnw test 

      - name: Build app (docker compose)
        run: docker compose build

      - name: Launch containers in background
        run: docker compose up -d

      - name: Verify service
        run: |
          sleep 15
          docker compose logs app

          echo "Checking server status"
          RESPONSE=$(curl -s http://localhost:8080/api/status)
          if [ "$RESPONSE" == "Ready!" ]; then
            echo "Success: Server is ready "
          else
            echo "Error: Expecting 'Ready!',  got '$RESPONSE'"
            exit 1
          fi
